version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root123$$
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123$$
      ME_CONFIG_MONGODB_SERVER: mongo

  # node-app:
  #   build: .
  #   container_name: hikaru-server
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URI=mongodb://admin:root123$$@mongo:27017/hikaru?authSource=admin
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm run dev

volumes:
  mongo-data:
  mongo-config:
